version: "3.7"

services:
  api:
    image: webdevops/php-apache:8.2-alpine
    container_name: Apache-PHP
    tty: true
    ports:
      - "8800:80"
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      WEB_DOCUMENT_ROOT: /app
    links:
      - database

  web:
    image: node:18.15.0-alpine
    container_name: front-reactJs
    tty: true
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm start"
    links:
      - api

  database:
    image: postgres:15.2-alpine3.17
    container_name: PostgreSQL
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: devDB@2023
      POSTGRES_DB: Market
    volumes:
      - postgres-data:/var/lib/postgres
      - ./database/DatabaseStruct.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres-data: